### ISSUE TITLE
liblktlang did not build

### ISSUE THREAD

**Issue by tinomai** [AdaCore/langkit#659]
The liblktlang build part fails with the following error:

```
Generating source for liblktlang...
Traceback (most recent call last):
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/libmanage.py", line 691, in run_no_exit
    parsed_args.func(parsed_args, unknown_args)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/libmanage.py", line 353, in wrapper
    cb_single(parsed_args)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/libmanage.py", line 1167, in do_make
    self.do_generate(args)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/libmanage.py", line 796, in do_generate
    self.context.emit()
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/compile_context.py", line 2090, in emit
    self.run_passes(self.all_passes)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/compile_context.py", line 2422, in run_passes
    pass_manager.run(self)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/passes.py", line 78, in run
    p.run(context)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/passes.py", line 273, in run
    self.pass_fn(context.emitter, context)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/emitter.py", line 403, in merge_support_libraries
    error(
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/diagnostics.py", line 376, in error
    check_source_language(False, message, ok_for_codegen=ok_for_codegen)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/diagnostics.py", line 431, in check_source_language
    location = get_current_location()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/diagnostics.py", line 345, in get_current_location
    assert ctx
           ^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/langkit/contrib/python/./manage.py", line 23, in <module>
    Manage().run()
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/libmanage.py", line 622, in run
    return_code = self.run_no_exit(argv)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/libmanage.py", line 717, in run_no_exit
    check_source_language(False, str(e), do_raise=False)
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/diagnostics.py", line 431, in check_source_language
    location = get_current_location()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/venv/lib/python3.11/site-packages/langkit/diagnostics.py", line 345, in get_current_location
    assert ctx
           ^^^
AssertionError
Traceback (most recent call last):
  File "/var/tmp/langkit/manage.py", line 435, in <module>
    args.func(args, unknown_args)
  File "/var/tmp/langkit/manage.py", line 135, in wrapper
    fn(args)
  File "/var/tmp/langkit/manage.py", line 343, in make
    assert m1.returncode == 0
           ^^^^^^^^^^^^^^^^^^
AssertionError
```
The langkit-support part builds fine.

I build langkit with
```
pip install -r requirements-pypi.txt
pip install .
python3 manage.py make --no-mypy --library-types=static,static-pic,relocatable
```
This issue affects at least 25.0.0 and master.

**Comment by pmderodat** [comment]
Hello,

The assertion failure is clearly a bug in Langkit: we are in the process of fixing it. After the fix, the actual issue is correctly reported:

```
error: AdaSAT must be checked out at '<langkit_root>/langkit/adasat' or its project file be reachable from the 'GPR_PROJECT_PATH' environment variable in order to build a standalone library.
```

I suppose you need to follow the following setup step (from the [README](https://github.com/AdaCore/langkit/blob/master/README.md):
> First, clone the adasat repository in the langkit subdirectory of the langkit repository:
>
> ```
> $ (cd langkit; git clone https://github.com/AdaCore/adasat)
> ```

**Comment by pmderodat** [comment]
The assertion failure should be fixed after https://github.com/AdaCore/langkit/commit/bc34d8ef768b027c099e226a954808eb1348706d

I’ll now close this, but please let us know if you still have trouble building Langkit. Thank you for reporting this!

**Comment by andrewathalye** [comment]
This isn’t fixed as far as I can tell, I still run in to it just now when building libadalang instead

**Comment by pmderodat** [comment]
Sorry, we can’t reproduce. Do you get exactly the same stack trace?

**Comment by andrewathalye** [comment]
Yes, exactly the same issue with `assert ctx` failing in `get_current_location`

I suspect it’s related to my other issue with adasat not being found properly

There’s probably not much to do from your end, but imo the dependency situation with AdaCore packages and libadalang isn’t ideal, it would be very nice if we could rewire Alire slightly and have it work as a makefile or ninja generator instead.

That’s out of scope though, thanks for trying to reproduce
